### ISSUE TITLE
图标有一些问题

### ISSUE THREAD

**Issue by Syize** [funnyzak/react-native-v2ex#1]
**Describe the bug**
安装apk时，包安装器显示图标，但是launcher不会显示

**Expected behavior**

**Current Behavior**
如图
![Screenshot_20220317-104754_Pixel Launcher~2.png](https://user-images.githubusercontent.com/44666294/158726753-05e24656-856e-496e-ab55-8b43c3214715.png)

**Steps to Reproduce**
Please provide detailed steps for reproducing the issue.

1. Navigate to...
2. Press on...
3. Scroll to...
4. See error...

**Screenshots**

**Smartphone (please complete the following information):**

- Device: 红米K40
- OS: crDroid，安卓12
- Version crDroid 8.2
- Launcher: nikgapps pixel launcher

**Additional context**

**Comment by funnyzak** [comment]
OK，晚点看下

**Comment by funnyzak** [comment]
已修复，[下载新版](https://github.com/funnyzak/react-native-v2ex/releases/latest)覆盖安装下。
