### ISSUE TITLE
webstorm编译出错

### ISSUE THREAD

**Issue by yesyeey** [funnyzak/react-native-v2ex#73]
请较下大佬 :
rn 0.67.2 ,node:16.5.1,
 npx react-native run-android
出现以下错误，新手测试了一天没找到原因，大佬可以看下什么问题引起的吗？
 
![image](https://user-images.githubusercontent.com/17378448/174580482-0e516402-4984-4d7f-b784-b5d4f6604ab5.png)

**Comment by hu-qi** [comment]
看报错是提示文件不存在，检查一下
`
src/components/common/Placeholder.tsx
`
这个文件是否正常

**Comment by yesyeey** [comment]
文件也存在，好奇怪 ，注释掉就好了，vscode 也一样
